# Generated by Django 5.1.1 on 2024-09-23 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category/category-icon-image')),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.productcategory')),
                ('total_items', models.ManyToManyField(to='Store.size')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
