# Generated by Django 5.1.1 on 2024-09-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_categorys_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys',
            name='total_items',
        ),
        migrations.AddField(
            model_name='categorys',
            name='total_items',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
