# Generated by Django 5.1.1 on 2024-09-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_remove_categorys_total_items_categorys_total_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys',
            name='total_items',
        ),
    ]
