# Generated by Django 5.1.1 on 2024-09-24 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_banner_offerbanner_supportsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('detail_description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='Blog-image')),
                ('img1', models.ImageField(upload_to='Blog-image')),
                ('img2', models.ImageField(upload_to='Blog-image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.productcategory')),
            ],
        ),
    ]
