# Generated by Django 5.1.1 on 2024-09-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_blog_short_description1_blog_short_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_description3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
