# Generated by Django 5.1.1 on 2024-09-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_blog_short_description3'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
    ]
