# Generated by Django 5.1.1 on 2024-09-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_privacypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('description3', models.TextField(blank=True, null=True)),
                ('description4', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='About_us-image')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='About_us-image')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='About_us-image')),
            ],
        ),
    ]
