# Generated by Django 5.1.1 on 2024-09-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContectUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contect1', models.CharField(max_length=255)),
                ('contect2', models.CharField(blank=True, max_length=255, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
                ('locations', models.URLField()),
            ],
        ),
    ]
