# Generated by Django 5.1.1 on 2024-09-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_contectus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact1', models.CharField(max_length=255)),
                ('contact2', models.CharField(blank=True, max_length=255, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
                ('locations', models.URLField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ContectUs',
        ),
    ]
