# Generated by Django 5.1.1 on 2024-09-27 15:18

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_contactus_delete_contectus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='contact2',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact1',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
    ]
