# Generated by Django 5.1.1 on 2024-09-27 15:19

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_remove_contactus_contact2_alter_contactus_contact1'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='contact2',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
    ]
