# Generated by Django 5.1.1 on 2024-09-27 17:26

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_contactus_contact2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, auto_now_add=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('massage', models.TextField(max_length=255)),
            ],
        ),
    ]
