# Generated by Django 5.1.1 on 2024-09-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_contactmassage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmassage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
