# Generated by Django 5.1.1 on 2024-09-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_alter_contactmassage_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMassage',
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
