# Generated by Django 5.1.1 on 2024-09-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0024_websiteinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteinfo',
            old_name='mail1',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='websiteinfo',
            old_name='mail2',
            new_name='email2',
        ),
    ]
