# Generated by Django 5.1.1 on 2024-10-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0027_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
