# Generated by Django 5.1.1 on 2024-10-02 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0029_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.coupon'),
        ),
    ]
