# Generated by Django 5.1.1 on 2024-10-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0030_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash On Delivery', 'Cash On Delivery'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket'), ('Upay', 'Upay')], max_length=30, null=True),
        ),
    ]
