# Generated by Django 5.1.1 on 2024-10-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0031_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
