# Generated by Django 5.1.1 on 2024-10-05 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0034_rename_coupon_order_coupon_alter_coupon_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 9, 48, 44, 399695, tzinfo=datetime.timezone.utc)),
        ),
    ]
