# Generated by Django 5.1.1 on 2024-10-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0038_division_district_subdistrict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='division',
        ),
        migrations.RemoveField(
            model_name='subdistrict',
            name='district',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='SubDistrict',
        ),
    ]
