# Generated by Django 5.1.1 on 2024-10-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0039_remove_district_division_remove_subdistrict_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
