# Generated by Django 5.1.1 on 2024-10-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0042_rename_category_productcategory_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='faq',
        ),
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
        migrations.DeleteModel(
            name='TermsCondition',
        ),
    ]
