# Generated by Django 5.1.1 on 2024-10-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0043_delete_aboutus_delete_faq_delete_privacypolicy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='detail_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='short_description1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='short_description2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='short_description3',
        ),
    ]
