# Generated by Django 5.1.1 on 2024-10-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0044_remove_blog_detail_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='details_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
