# Generated by Django 5.1.1 on 2024-10-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0045_blog_details_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
