# Generated by Django 5.1.1 on 2024-10-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutus_faq_privacypolicy_termscondition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='description4',
        ),
    ]
