# Generated by Django 5.1.1 on 2024-10-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('Inside Dhaka', 'Inside Dhaka'), ('Outside Dhaka', 'Outside Dhaka')], max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
